### ISSUE TITLE
Can inference be done with CPU and if so, is it painfully slow?

### ISSUE THREAD

**Issue by flesler** [artidoro/qlora#107]
Assuming a not very large model, like 7b-13b, is it feasible to infer with CPU?

**Comment by Oxi84** [comment]
4 bit seem around 2x slower than fp16 on GPU.

**Comment by flesler** [comment]
Ok, the question is about CPU though, not GPU

**Comment by artidoro** [comment]
QLoRA is primarily a memory efficient method. 

4-bit QLoRA training speed is roughly on par with 16-bit LoRA. However, it is true that inference is currently slow. We are working on improving 4-bit inference. 

Regarding the original question, unfortunately, QLoRA only works on GPU.

**Comment by flesler** [comment]
Thanks :+1:

**Comment by Oxi84** [comment]
> QLoRA is primarily a memory efficient method.
> 
> 4-bit QLoRA training speed is roughly on par with 16-bit LoRA. However, it is true that inference is currently slow. We are working on improving 4-bit inference.
> 
> Regarding the original question, unfortunately, QLoRA only works on GPU.

It is already impressive to make it use 8x less memory than fp32.

For 4bit inteference, is it slow because you need to de-quantize some values to fp16 or fp32 for neural network?

**Comment by Oxi84** [comment]
> Assuming a not very large model, like 7b-13b, is it feasible to infer with CPU?

Llama c++ is probably the best for CPU, once you train it via qlora and merge the lora weight into a full-size model. But I guess it would be less than 20 tokens/sec for 7B on 13900K. rtx4900K (with auto-gptq)
 for 7B gets around 100 tokens/sec maybe even more, and you can do multiple batches in one request to get larger effective speed.

**Comment by flesler** [comment]
> > Assuming a not very large model, like 7b-13b, is it feasible to infer with CPU?
> 
> Llama c++ is probably the best for CPU, once you train it via qlora and merge the lora weight into a full-size model.

@Oxi84 that sounds interesting, do you have a link where that’s explained? would the resulting model still be fp4?

**Comment by tabacof** [comment]
I am also interested to know how to merge QLoRA back into a full-sized model. I tried using `model.merge_and_unload` but it didn't work when pushing to Hugging Face / saving using Torch.

Does anyone have such an example?

**Comment by LeoPerelli** [comment]
Hi all. Wondering why does QLora only work for GPU, bot not for CPUs? @artidoro Thanks!
