### ISSUE TITLE
Why is the source_max_len parameter 16 in finetune_guanaco_XX.sh

### ISSUE THREAD

**Issue by li-aolong** [artidoro/qlora#142]
The length of training data is longer than 16. Whyi the parameter is set to 16?

**Comment by artidoro** [comment]
the input text is essentially just the start token, we put all the text in the target field.

**Comment by li-aolong** [comment]
I see. Thank you.

**Comment by usmanxia** [comment]
> 

Hi @artidoro 

Can you please explain this point? For alpaca dataset format, there are instruction, input and output fields. What does target field specify?
