### ISSUE TITLE
Training with Deepspeed 3?

### ISSUE THREAD

**Issue by BabyChouSr** [artidoro/qlora#162]
Has anyone tried finetuning with deepspeed 3? I tried QLoRA with deepspeed 2 and it seems to work, but deepspeed 3 runs into the error where I can't pass in a device map. And, if I don't pass in a device map, then I run into the error where the tensors are on different devices.

**Comment by luckystar1992** [comment]
hello， do you train model with deepspeed stage2 config on seconde pretraining task? and can you share your stage config files, my traning job seems worked, but I am not sure if it really works!!

**Comment by BabyChouSr** [comment]
Used the config based on https://github.com/git-cloner/llama-lora-fine-tuning/tree/main

**Comment by BabyChouSr** [comment]
Closed since it's not possible currently.

**Comment by Nisoka** [comment]
@BabyChouSr  Hi, can you give me an example about use qlora with deepspeed?

**Comment by BabyChouSr** [comment]
You can check it out here: https://github.com/lm-sys/FastChat/blob/main/docs/training.md

**Comment by Nisoka** [comment]
Thank you!
