### ISSUE TITLE
Question above VRAM during training with QLoRA

### ISSUE THREAD

**Issue by iumyx2612** [artidoro/qlora#168]
In the paper, authors stated that: "In practice, this means whenever a QLoRA weight tensor is used, we dequantize the tensor to BFloat16, and then perform a matrix multiplication in 16-bit". When converting a "4-bit" weight tensor back to 16-bit weight tensor, the VRAM usage of the model should go back to normal like finetuning LoRA with BF16 no?

**Comment by artidoro** [comment]
This happens for each matrix separately. So most of the model is still encoded in 4bits. The dequantization to 16bits happens only for the layers that are being used for a computation. This maintains the memory benefits while ensuring that we use 16bits precision for computations.

**Comment by iumyx2612** [comment]
> This happens for each matrix separately. So most of the model is still encoded in 4bits. The dequantization to 16bits happens only for the layers that are being used for a computation. This maintains the memory benefits while ensuring that we use 16bits precision for computations.

Thank you, now I understand why VRAM usage stays low!
