### ISSUE TITLE
ValueError: You can't train a model that has been loaded in 8-bit precision on a different device than the one you're training on.

### ISSUE THREAD

**Issue by zhaoyang110157** [artidoro/qlora#186]
I'm new to this field and want to try it out. I met this problem when trying to run the shell (finetune_guanaco_7b.sh) or "python qlora.py –learning_rate 0.0001 --model_name_or_path huggyllama/llama-7b" . Here's the information and need your help.

First, this is my environment: python 3.9.16,   torch 2.0.1+cu118 ,   torchvision 0.15.2+cu118 ,    the requirements.txt

Second, I met the problem “ out of memory ” when running on multiple A100 with 80G and so I modified the code of qlora.py in line 267 and set the cuda from "auto" into a preset cuda "cuda:1".  I thought it must be another program took the space and I set this program to a free GPU. 

```
def get_accelerate_model(args, checkpoint_dir):
    n_gpus = torch.cuda.device_count()
    max_memory = f'{args.max_memory_MB}MB'
    max_memory = {i: max_memory for i in range(n_gpus)}
    device_map = "cuda:1" #******
```

This error left. But it still turns to fail with another error and I barely know how to solve it.
`ValueError: You can't train a model that has been loaded in 8-bit precision on a different device than the one you're training on. Make sure you loaded the model on the correct device using for example device_map={'':torch.cuda.current_device()}you're training on. Make sure you loaded the model on the correct device using for example device_map={'':torch.cuda.current_device() or device_map={'':torch.xpu.current_device()}`

I thought It might be here and I turned it into:
```
def get_accelerate_model(args, checkpoint_dir):
    n_gpus = torch.cuda.device_count()
    max_memory = f'{args.max_memory_MB}MB'
    max_memory = {i: max_memory for i in range(n_gpus)}
    device_map = {'':'cuda:1'} #******
```
It returns the same.

**********************************************************

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes  

and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

bin /home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/learner/anaconda3/envs/StockQlora did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
loading base model huggyllama/llama-7b...
/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/modeling_utils.py:2192: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:14<00:00,  7.01s/it]
adding LoRA modules...
trainable params: 79953920.0 || all params: 3660320768 || trainable: 2.184341894267557
loaded model
Adding special tokens.
Downloading readme: 7.47kB [00:00, 3.14MB/s]
Downloading and preparing dataset parquet/tatsu-lab--alpaca to /home/learner/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7...
Downloading data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24.2M/24.2M [00:00<00:00, 53.7MB/s]
Downloading data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.23s/it]
Extracting data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1272.16it/s]
Dataset parquet downloaded and prepared to /home/learner/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7. Subsequent calls will reuse this data.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 389.26it/s]
torch.float32 422326272 0.11537932153507864                                                                                                                              
torch.uint8 3238002688 0.8846206784649213
Traceback (most recent call last):
  File "/home/learner/qlora/qlora.py", line 807, in <module>
    train()
  File "/home/learner/qlora/qlora.py", line 769, in train
    train_result = trainer.train()
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/trainer.py", line 1531, in train
    return inner_training_loop(
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/trainer.py", line 1642, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1198, in prepare
    result = tuple(
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1199, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1026, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1277, in prepare_model
    raise ValueError(
ValueError: You can't train a model that has been loaded in 8-bit precision on a different device than the one you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device()}you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device() or device_map={'':torch.xpu.current_device()}

**Comment by zhaoyang110157** [comment]
I thought This might be a similar one like [this issue #peft 414 ](https://github.com/huggingface/peft/issues/414), but obviously update accelerate didn't help.

**Comment by zhaoyang110157** [comment]
And the multiple information in README.md, I didn't get it. As the function 'get_accelerate_model' did pass the 'device_map' and 'max_memory'. Maybe this is where the problem is, or the device_map I changed mentioned before.

**Comment by zhaoyang110157** [comment]
I tried `device_map={'':torch.cuda.current_device()}` but it brings back OOM.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/learner/anaconda3/envs/StockQlora did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
loading base model huggyllama/llama-7b...
/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/modeling_utils.py:2192: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.95s/it]
adding LoRA modules...
trainable params: 79953920.0 || all params: 3660320768 || trainable: 2.184341894267557
loaded model
Adding special tokens.
Found cached dataset json (/home/learner/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-6126c710748182cf/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 814.43it/s]
Loading cached processed dataset at /home/learner/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-6126c710748182cf/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-5059a35543c3ee43.arrow
Loading cached processed dataset at /home/learner/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-6126c710748182cf/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-c34aca175df1ad67.arrow
Splitting train dataset in train and validation according to `eval_dataset_size`
Loading cached split indices for dataset at /home/learner/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-6126c710748182cf/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-f50131f21715d524.arrow and /home/learner/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-6126c710748182cf/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-16d69901a69c3462.arrow
Loading cached processed dataset at /home/learner/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-6126c710748182cf/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-bed03f96453b8cd7.arrow
Loading cached processed dataset at /home/learner/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-6126c710748182cf/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96/cache-5be43d05908a715e.arrow
Found cached dataset json (/home/learner/.cache/huggingface/datasets/json/default-f6287e10f5dbf402/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 681.78it/s]
torch.bfloat16 422060032 0.1153065849032323
torch.uint8 3238002688 0.8846206784649213
torch.float32 266240 7.273663184633547e-05
  0%|                                                                                                                                           | 0/1875 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/learner/qlora/qlora.py", line 807, in <module>
    train()
  File "/home/learner/qlora/qlora.py", line 769, in train
    train_result = trainer.train()
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/trainer.py", line 1531, in train
    return inner_training_loop(
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/trainer.py", line 1795, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/chen19/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/trainer.py", line 2640, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/trainer.py", line 2665, in compute_loss
    outputs = model(**inputs)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/parallel/scatter_gather.py", line 53, in scatter_kwargs
    kwargs = scatter(kwargs, target_gpus, dim) if kwargs else []
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/parallel/scatter_gather.py", line 44, in scatter
    res = scatter_map(inputs)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_map
    return [type(obj)(i) for i in zip(*map(scatter_map, obj.items()))]
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/parallel/scatter_gather.py", line 31, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/parallel/scatter_gather.py", line 27, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/parallel/_functions.py", line 96, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/torch/nn/parallel/comm.py", line 189, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error: out of memory
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  0%|          | 0/1875 [00:02<?, ?it/s]

**Comment by zhaoyang110157** [comment]
When I turned the device into "cpu", it returns another error.
Traceback (most recent call last):
  File "/home/learner/qlora/qlora.py", line 806, in <module>
    train()
  File "/home/learner/qlora/qlora.py", line 768, in train
    train_result = trainer.train()
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/trainer.py", line 1531, in train
    return inner_training_loop(
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/transformers/trainer.py", line 1642, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1198, in prepare
    result = tuple(
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1199, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1026, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/learner/anaconda3/envs/StockQlora/lib/python3.9/site-packages/accelerate/accelerator.py", line 1274, in prepare_model
    if torch.device(current_device_index) != self.device:
TypeError: Device() received an invalid combination of arguments - got (NoneType), but expected one of:
 * (torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType)
 * (str type, int index)

**Comment by FHL1998** [comment]
Try to update the accelerate version.

**Comment by zhaoyang110157** [comment]
> Try to update the accelerate version.

Well, I tried but it's not the same problem like this one ( https://github.com/huggingface/peft/issues/414). My accelerate already been 0.21.0.dev0  and pip install returns 'already satisfied'. But thanks.

**Comment by FHL1998** [comment]
Have you installed `einops` ? Yeah, I can run the code but the results is poor. The GPU I use is A100-80GB.

**Comment by FHL1998** [comment]
> > einops
> 
> Already installed. You can successfully run the code in A100-80GB, and I get the same GPU, then the only difference should be that I got multiple gpu and it brings me this error? What should I do with that?

Actually I used 3 A100 GPUs, check the following requirements.txt (`transformers==4.30.0`):

```
bitsandbytes==0.39.0
transformers @ git+https://github.com/huggingface/transformers.git
peft @ git+https://github.com/huggingface/peft.git
accelerate @ git+https://github.com/huggingface/accelerate.git
einops==0.6.1
evaluate==0.4.0
scikit-learn==1.2.2
sentencepiece==0.1.99
wandb==0.15.3
torch
torchvision
torchaudio
datasets
scipy
nltk
rouge_score
evaluate
gradio
einop
```

**Comment by zhaoyang110157** [comment]
> > > einops
> > 
> > 
> > Already installed. You can successfully run the code in A100-80GB, and I get the same GPU, then the only difference should be that I got multiple gpu and it brings me this error? What should I do with that?
> 
> Actually I used 3 A100 GPUs, check the following requirements.txt (`transformers==4.30.0`):
> 
> ```
> bitsandbytes==0.39.0
> transformers @ git+https://github.com/huggingface/transformers.git
> peft @ git+https://github.com/huggingface/peft.git
> accelerate @ git+https://github.com/huggingface/accelerate.git
> einops==0.6.1
> evaluate==0.4.0
> scikit-learn==1.2.2
> sentencepiece==0.1.99
> wandb==0.15.3
> torch
> torchvision
> torchaudio
> datasets
> scipy
> nltk
> rouge_score
> evaluate
> gradio
> einop
> ```

I tried it and it brings the same error. Thanks anyway.

**Comment by zhaoyang110157** [comment]
It seems that the code is default trained on the first gpu, but that gpu is occupied by other program. So when I run it, I set auto and it used the cuda:0, but it's OOM. But when I set it to the free gpu like cuda:6 / cuda:7, it loads the model there but trains on the cuda:0. It might be the reason and I can't find any other explanation as others can run the model on multiple A100-80GB which means it's not the fault of quantification and code.  

I got to figure out the set of the train() and wish me luck. Thanks for help @FHL1998

**Comment by yeeeqichen** [comment]
> It seems that the code is default trained on the first gpu, but that gpu is occupied by other program. So when I run it, I set auto and it used the cuda:0, but it's OOM. But when I set it to the free gpu like cuda:6 / cuda:7, it loads the model there but trains on the cuda:0. It might be the reason and I can't find any other explanation as others can run the model on multiple A100-80GB which means it's not the fault of quantification and code.
> 
> I got to figure out the set of the train() and wish me luck. Thanks for help @FHL1998

Maybe you shouldn't modify the codes, but use `CUDA_VISIBLE_DEVICES=1,2,3 bash finetune_guanaco_7b.sh` instead.

**Comment by zhaoyang110157** [comment]
> > It seems that the code is default trained on the first gpu, but that gpu is occupied by other program. So when I run it, I set auto and it used the cuda:0, but it's OOM. But when I set it to the free gpu like cuda:6 / cuda:7, it loads the model there but trains on the cuda:0. It might be the reason and I can't find any other explanation as others can run the model on multiple A100-80GB which means it's not the fault of quantification and code.
> > I got to figure out the set of the train() and wish me luck. Thanks for help @FHL1998
> 
> Maybe you shouldn't modify the codes, but use `CUDA_VISIBLE_DEVICES=1,2,3 bash finetune_guanaco_7b.sh` instead.

Oh, my Goddess, it works.  Thank you very much.  I really appreciate it. You solved the problem I've been suffering from these days.

**Comment by YanJiaHuan** [comment]
Run on T5-flan-base, 8*A6000 48G server, can use CUDA_VISIABLE_DEVICES to launch by set (= 0 | 0,1 | 0,1,2), but when use more than 3 GPUs, the same "ValueError: You can't train a model that has been loaded in 8-bit precision on a different device than the one you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device()}you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device() or device_map={'':torch.xpu.current_device()}" error occured.

**Comment by Titus-von-Koeller** [comment]
Thanks @YanJiaHuan:

`device_map={'':torch.cuda.current_device()}`

fixed the error for me on a 4 GPU setup.

Full example:
```python
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    load_in_4bit=True,
    device_map={'':torch.cuda.current_device()},  # fix for >3 GPUs
)
```

**Comment by Titus-von-Koeller** [comment]
Actually, when running a single test, it worked, but not when run as part of a larger test suite. I guess `cuda0` must still have been in use or sth. Since this was a single GPU test, `device_map={'': 'cuda:0'}` did the job in my case.

**Comment by raeidsaqur** [comment]
Yes, `device_map` should work. Check `xpu` and use `PartialState` if using `accelerate`. 

```
from accelerate import PartialState
from trl import  is_xpu_available

device_map = (
            {"": f"xpu:{PartialState().local_process_index}"}
            if is_xpu_available()
            else {"": PartialState().local_process_index}
        )
       ...
model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map=device_map,
            quantization_config=quantization_config,
            torch_dtype=torch_dtype,
     )
```

**Comment by u1vi** [comment]
Little addition. I have tried all the suggested solutions but did not help me. 

It took one day to find it :

```
from accelerate import PartialState

model = AutoModelForCausalLM.from_pretrained(
  script_args.model_name_or_path,
  low_cpu_mem_usage=True,
  torch_dtype=torch.float16,
  load_in_4bit=True,
  device_map={"": PartialState().process_index},)
```

**Comment by rupakdas18** [comment]
This is how I solved my issue:
Before running my script, I ran the command below. In my case, I wanted to use either GPU 3, 4, or 5 (other GPUs were highly loaded by other users)
>export CUDA_VISIBLE_DEVICES=3,4,5

Inside my Python script, I used these commands,

>import os
>os.environ["TOKENIZERS_PARALLELISM"] = "false"
>CUDA_LAUNCH_BLOCKING=1

>desired_device = 0
>torch.cuda.set_device(desired_device)
............

>model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=compute_dtype,
    quantization_config=bnb_config,
    device_map = torch.cuda.set_device(desired_device)
)

....................

My guess is the system is now considering GPU 3 as GPU 0 (default GPU) because of the "export CUDA_VISIBLE_DEVICES=3,4,5" command. Because, after the export command, I tried to see all the available GPUs and system gave me this output,

Number of available GPUs: 3
GPU 0: NVIDIA A100-SXM4-80GB
  Compute Capability: (8, 0)
  Memory: 79.20 GB
GPU 1: NVIDIA A100-SXM4-80GB
  Compute Capability: (8, 0)
  Memory: 79.20 GB
GPU 2: NVIDIA A100-SXM4-80GB
  Compute Capability: (8, 0)
  Memory: 79.20 GB
