### ISSUE TITLE
LoRA for embeddings layer

### ISSUE THREAD

**Issue by Andrei-Aksionov** [artidoro/qlora#210]
Hi there 👋 

I'm not sure if it's a proper place to ask this type of questions. Sorry in advance.

In the [paper](https://arxiv.org/pdf/2305.14314.pdf) on page 6 there is a statement:
> we find that the most critical LoRA hyper-parameter is how many LoRA adapters are used in
total and that LoRA on all linear transformer block layers are required to match full finetuning
performance

But what about LoRA for embeddings layer? It's supported in [LoRA repo](https://github.com/microsoft/LoRA/blob/main/loralib/layers.py#L32). Have you tried it in your experiments?

**Comment by artidoro** [comment]
We have not tried this in our experiments but I think it would be quite interesting! LoRA layer for embedding would need to be supported by PEFT and we did not implement it. This might be useful when training on a new language or domain.

**Comment by Andrei-Aksionov** [comment]
Thanks for the reply.
