### ISSUE TITLE
Notebook Code for qlora doesn't work

### ISSUE THREAD

**Issue by nivibilla** [artidoro/qlora#224]
`None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

When enabling gradient checkpointing in the notebook trainer. It doesn't work

**Comment by nivibilla** [comment]
Fixed by `ddp_find_unused_parameters=False`

**Comment by artidoro** [comment]
Is the notebook broken or is it a different setting than the standard single GPU colab?

**Comment by nivibilla** [comment]
I'm not sure, I did it in databricks. So maybe it's a databricks issue. But I think it's because the system thinks there's multiple gpus even though there aren't. So having that flag fixes it. So it could just be a databricks issue.
