### ISSUE TITLE
Parameters source_max_len & target_max_len

### ISSUE THREAD

**Issue by usmanxia** [artidoro/qlora#227]
Hi !

 Can anyone please confirm that parameters source_max_len & target_max_len are the length os input and outputs respectively? Meaning if we have set --source_max_len 16     --target_max_len 512 it means our instruction cannot be more than 16 tokens and output will be max 512 tokens?

Regards

**Comment by BugReporterZ** [comment]
I can confirm (or at least, it is my understanding) that in this case "source" means "input", and that "target" means "output".
It took me a while to figure out the terminology initially.

**Comment by usmanxia** [comment]
Thank you @BugReporterZ
So we should make sure that our text in *instruction* is not more than 16? And if it is less than 16, I ll get padded to be 16.

**Comment by BugReporterZ** [comment]
Yes, it shouldn't be larger or it will be truncated.

In my case, I set both source_max and target_max lengths to a high value and adjust lengths as required when building my datasets (from source files) rather than just naively truncating lengths, but this might not always be possible.

**Comment by usmanxia** [comment]
Got it, thank you.

Yes I just needed to tune this to see if it has impact on training and inference time. It takes around 25 seconds for inference and 45 seconds for training/iter on a 3090 GPU with 24 GB RAM.

So guess will try to reduce input and outside optimally to see if it has some effect.

**Comment by AaronZLT** [comment]
Confused, how to adjust the sequence length? By setting source_max and target_max?
