### ISSUE TITLE
Adapter model is just 400 bytes when using finetune.py

### ISSUE THREAD

**Issue by KKcorps** [artidoro/qlora#38]
I am using the `finetune.py` script with default params

it works perfectly but when I get the adapter model in the checkpoint directory, the size of adapter model is just 400 bytes.

What can be the reason for this?

**Comment by s1ghhh** [comment]
check your peft version and try:
`pip uninstall peft -y`
`pip install git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08 `

**Comment by taishan1994** [comment]
> check your peft version and try: `pip uninstall peft -y` `pip install git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08 `

it doesn't work. peft version must be 0.4.0.dev.0. but i also meet this problem.

**Comment by KKcorps** [comment]
Yes @taishan1994 is correct, we can't use older version of peft since it doesn't have the qlora changes.
