### ISSUE TITLE
ValueError: paged_adamw_32bit is not a valid OptimizerNames

### ISSUE THREAD

**Issue by lxuechen** [artidoro/qlora#4]
Trying to run the basic training script but getting this error. Is there a particular branch of `transformers` I should install?

**Comment by artidoro** [comment]
Hey! Thanks a lot for your interest in QLoRA. The necessary changes to use QLoRA will be merged in the transformers library tomorrow morning and we will update this repo with installation instructions.

**Comment by diegomontoya** [comment]
Temp fix via: https://github.com/artidoro/qlora/issues/5#issuecomment-1560515696

**Comment by lxuechen** [comment]
Fixed after nightly install.
