### ISSUE TITLE
Question: what dataset was guanaco trained on?

### ISSUE THREAD

**Issue by getorca** [artidoro/qlora#7]
what dataset was guanaco trained on?

**Comment by artidoro** [comment]
We'll update soon with the exact dataset. In the meantime, the processing steps for OASST1 are described in the paper.

**Comment by winglian** [comment]
here my pass at generating their dataset. Just use the first human and assistant row turn from each row for the guanaco dataset. We went ahead and found the highest ranked entire conversation chain for the dataset. https://huggingface.co/datasets/openaccess-ai-collective/oasst1-guanaco-extended

**Comment by artidoro** [comment]
I also added the dataset info to the readme. Thanks!
