### ISSUE TITLE
Question : what loss value is good value ?

### ISSUE THREAD

**Issue by x4080** [artidoro/qlora#89]
In training what loss value is good value ?
under 1 ?

and if we run max_steps=10, and in step 3, the value is 0.3 for example, can we stop it and the model is getting that loss value ?
In this context I'm using colab qlora example from HF

**Comment by phalexo** [comment]
It is not the absolute value of loss per se, but rather when it stops decreasing, reaches an inflection point.

**Comment by x4080** [comment]
ok thanks
