### ISSUE TITLE
How to use the fine-turned model?

### ISSUE THREAD

**Issue by tulunlxj2017** [artidoro/qlora#91]
fineturn.sh successfully ended
![image](https://github.com/artidoro/qlora/assets/32868572/5499b122-5828-454c-9f7b-f7299974802f)

After fine-turning , I got these file in ./output directory, but I don't see any file is likely be the fine-turned model.
![image](https://github.com/artidoro/qlora/assets/32868572/e4055282-f4f4-424e-b550-538c7d135ac3)

Does anyone know where to find the fine-turned model or how to use it with llama.cpp? please help

**Comment by mhenrichsen** [comment]
The checkpoints are your LoRa. Just copy the folder into the Lora folder in llama.cpp.
